### ISSUE TITLE
Suggestion: Transition from setup.py to Poetry for Better Package and Dependency Management

### ISSUE THREAD

**Issue by yjmaxpayne** [qiboteam/qibotn#23]
@liweintu: Qibo repositories have mostly shifted to Poetry. In our ongoing effort to improve the development process and maintainability of our project, we are considering transitioning from `setup.py` to Poetry for package and dependency management. 

Poetry provides a more modern and intuitive approach to managing Python packages. It simplifies the process of setting up a new project, managing dependencies, and building and publishing packages. 

Thus, I'd like to put up this issue as a tracker for the team to consider shifting to poetry when the majority of the development tasks are completed to support the release of QiboTN.

**Comment by liweintu** [comment]
Closing now as it's completed in PR #26 .
